# Generated by Django 3.2.8 on 2021-10-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id1', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('id2', models.CharField(max_length=50)),
                ('id3', models.CharField(max_length=50)),
            ],
        ),
    ]
